(dp1
S'output'
p2
S"<type 'exceptions.KeyError'> 'is_valid'"
p3
sS'layer'
p4
S'/home/www-data/web2py/applications/reliefList/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f59d107aeb0, file "/home/www-data/web2py/applications/reliefList/controllers/default.py", line 2>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/www-data/web2py/applications/reliefList/controllers/default.py", line 198, in <module>\n  File "/home/www-data/web2py/gluon/globals.py", line 414, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/www-data/web2py/applications/reliefList/controllers/default.py", line 48, in productLocalAddress\n    if address_from[\'is_valid\'] == True:\n  File "/usr/local/lib/python2.7/dist-packages/shippo/resource.py", line 81, in __getitem__\n    raise err\nKeyError: \'is_valid\'\n'
p11
s.